name: 'finance_de_demo'
version: '1.0.0'
config-version: 2

profile: 'finance_de_demo'

flags:
  enable_iceberg_materializations: true

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_de_demo:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: MARTS
