finance_de_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SFSENORTHAMERICA-DEMO_JHILL
      role: ACCOUNTADMIN
      database: FINANCE_DE_DEMO
      warehouse: FINANCE_DE_DEMO_WH
      schema: MARTS
      threads: 4
