-- ============================================================================
-- Finance DE Demo :: Governance (2/4) - PII classification / tagging
-- Auto-classify the relational source, then set semantic/privacy tags explicitly
-- (names are not auto-detected on synthetic data; Iceberg tables need ALTER ICEBERG TABLE).
-- Run with: snow sql -c default -f sql/governance/10_classify.sql
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCE_DE_DEMO;

-- 1) Auto-classify + auto-tag the relational source (detects EMAIL, COUNTRY)
CALL ASSOCIATE_SEMANTIC_CATEGORY_TAGS('FINANCE_DE_DEMO.RAW.CUSTOMERS',
     EXTRACT_SEMANTIC_CATEGORIES('FINANCE_DE_DEMO.RAW.CUSTOMERS'));

-- 2) Explicitly tag name columns the auto-classifier misses on synthetic data
ALTER TABLE FINANCE_DE_DEMO.RAW.CUSTOMERS MODIFY COLUMN FIRST_NAME
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER TABLE FINANCE_DE_DEMO.RAW.CUSTOMERS MODIFY COLUMN LAST_NAME
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';

-- 3) Tag the Iceberg gold table columns (ALTER ICEBERG TABLE, not ALTER TABLE)
ALTER ICEBERG TABLE FINANCE_DE_DEMO.MARTS.INVESTOR_360 MODIFY COLUMN EMAIL
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'EMAIL', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER ICEBERG TABLE FINANCE_DE_DEMO.MARTS.INVESTOR_360 MODIFY COLUMN FIRST_NAME
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER ICEBERG TABLE FINANCE_DE_DEMO.MARTS.INVESTOR_360 MODIFY COLUMN LAST_NAME
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'IDENTIFIER';
ALTER ICEBERG TABLE FINANCE_DE_DEMO.MARTS.INVESTOR_360 MODIFY COLUMN COUNTRY
  SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'COUNTRY', SNOWFLAKE.CORE.PRIVACY_CATEGORY = 'QUASI_IDENTIFIER';

-- Verify
SELECT 'INVESTOR_360.EMAIL' col,
       SYSTEM$GET_TAG('SNOWFLAKE.CORE.PRIVACY_CATEGORY','FINANCE_DE_DEMO.MARTS.INVESTOR_360.EMAIL','COLUMN') AS privacy_category
UNION ALL SELECT 'INVESTOR_360.FIRST_NAME',
       SYSTEM$GET_TAG('SNOWFLAKE.CORE.PRIVACY_CATEGORY','FINANCE_DE_DEMO.MARTS.INVESTOR_360.FIRST_NAME','COLUMN');
